/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as RevolutPersonalTermsRouteImport } from './routes/revolut-personal/terms'
import { Route as RevolutPersonalPrivacyRouteImport } from './routes/revolut-personal/privacy'
import { Route as RevolutPersonalCallbackRouteImport } from './routes/revolut-personal/callback'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevolutPersonalTermsRoute = RevolutPersonalTermsRouteImport.update({
  id: '/revolut-personal/terms',
  path: '/revolut-personal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RevolutPersonalPrivacyRoute = RevolutPersonalPrivacyRouteImport.update({
  id: '/revolut-personal/privacy',
  path: '/revolut-personal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RevolutPersonalCallbackRoute = RevolutPersonalCallbackRouteImport.update({
  id: '/revolut-personal/callback',
  path: '/revolut-personal/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/revolut-personal/callback': typeof RevolutPersonalCallbackRoute
  '/revolut-personal/privacy': typeof RevolutPersonalPrivacyRoute
  '/revolut-personal/terms': typeof RevolutPersonalTermsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/revolut-personal/callback': typeof RevolutPersonalCallbackRoute
  '/revolut-personal/privacy': typeof RevolutPersonalPrivacyRoute
  '/revolut-personal/terms': typeof RevolutPersonalTermsRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/revolut-personal/callback': typeof RevolutPersonalCallbackRoute
  '/revolut-personal/privacy': typeof RevolutPersonalPrivacyRoute
  '/revolut-personal/terms': typeof RevolutPersonalTermsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/revolut-personal/callback'
    | '/revolut-personal/privacy'
    | '/revolut-personal/terms'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/revolut-personal/callback'
    | '/revolut-personal/privacy'
    | '/revolut-personal/terms'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/revolut-personal/callback'
    | '/revolut-personal/privacy'
    | '/revolut-personal/terms'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RevolutPersonalCallbackRoute: typeof RevolutPersonalCallbackRoute
  RevolutPersonalPrivacyRoute: typeof RevolutPersonalPrivacyRoute
  RevolutPersonalTermsRoute: typeof RevolutPersonalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revolut-personal/terms': {
      id: '/revolut-personal/terms'
      path: '/revolut-personal/terms'
      fullPath: '/revolut-personal/terms'
      preLoaderRoute: typeof RevolutPersonalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revolut-personal/privacy': {
      id: '/revolut-personal/privacy'
      path: '/revolut-personal/privacy'
      fullPath: '/revolut-personal/privacy'
      preLoaderRoute: typeof RevolutPersonalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revolut-personal/callback': {
      id: '/revolut-personal/callback'
      path: '/revolut-personal/callback'
      fullPath: '/revolut-personal/callback'
      preLoaderRoute: typeof RevolutPersonalCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  RevolutPersonalCallbackRoute: RevolutPersonalCallbackRoute,
  RevolutPersonalPrivacyRoute: RevolutPersonalPrivacyRoute,
  RevolutPersonalTermsRoute: RevolutPersonalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
